/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

#import "GameCenterManagerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class UITableView;

@interface AchievementHandler : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/ <UITableViewDataSource, UITableViewDelegate, GameCenterManagerDelegate>
{
    UITableView *table;
    int sectNumbers;
    int ptnTotal;
    int ptnCur;
    int achievementTotal;
    int achievementComplete;
    _Bool isLoadingError;
    struct CGRect showRect;
    int rowHeight;
    int middleFontSize;
    int smallFontSize;
    float extendedWidth;
}

- (void)setTable:(id)fp8;
- (id)table;
- (id).cxx_construct;
- (void)setTableVisible:(BOOL)fp8;
- (void)showTableForAchievement;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (int)getAchievementCurrentPoint;
- (int)getAchievementTotalPoint;
- (int)getAchievementComplete;
- (int)getAchievementTotalValue;
- (_Bool)getIsLoadingError;
- (void)deinitData;
- (void)initData;
- (void)hideTable;
- (void)dealloc;
- (id)init;

@end

