/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@class UIImage, UIImageView;

@interface ArtBookImageView : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
    UIImage *originImage;
    UIImageView *imageView;
    float origDistance;
    struct CGRect originFrame;
    BOOL bMultiTouch;
    struct CGPoint beginPoint;
    float minX;
    float offsetY;
    float minY;
    float offsetX;
}

- (id).cxx_construct;
- (void)scaleTo:(float)fp8;
- (float)spaceToPoint:(struct CGPoint)fp8 FromPoint:(struct CGPoint)fp16;
- (void)moveToX:(float)fp8 ToY:(float)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)setImage:(id)fp8;
- (_Bool)isScaled;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setImageViewBounds:(struct CGRect)fp8;

@end

