/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

struct AudioBuffer {
    unsigned int _field1;
    unsigned int _field2;
    void *_field3;
};

struct AudioBufferList {
    unsigned int _field1;
    struct AudioBuffer _field2[1];
};

struct CGAffineTransform {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
};

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct ChannelGroupI;

struct ChannelPool;

struct DSPResampler;

struct FMOD_OS_CRITICALSECTION;

struct FMOD_OS_LIBRARY;

struct FMOD_OS_SEMAPHORE;

struct FMOD_OUTPUT_DESCRIPTION_EX {
    char *_field1;
    unsigned int _field2;
    int _field3;
    void *_field4;
    void *_field5;
    void *_field6;
    void *_field7;
    void *_field8;
    void *_field9;
    void *_field10;
    void *_field11;
    void *_field12;
    void *_field13;
    struct LinkedListNode *_field14;
    struct LinkedListNode *_field15;
    void *_field16;
    int _field17;
    int _field18;
    struct FMOD_OS_LIBRARY *_field19;
    unsigned int _field20;
    void *_field21;
    void *_field22;
    void *_field23;
    void *_field24;
    void *_field25;
    void *_field26;
    void *_field27;
    void *_field28;
    void *_field29;
    void *_field30;
    void *_field31;
    void *_field32;
    void *_field33;
    void *_field34;
    void *_field35;
    void *_field36;
    void *_field37;
    void *_field38;
    void *_field39;
    void *_field40;
    void *_field41;
};

struct FMOD_RECORDING_INFO {
    struct LinkedListNode *_field1;
    struct LinkedListNode *_field2;
    void *_field3;
    int _field4;
    int _field5;
    struct {
        unsigned int _field1;
        unsigned short _field2;
        unsigned short _field3;
        unsigned char _field4[8];
    } _field6;
    _Bool _field7;
    int _field8;
    _Bool _field9;
    int _field10;
    unsigned int _field11;
    unsigned int _field12;
    struct SoundI *_field13;
    int _field14;
    int _field15;
    struct DSPResampler *_field16;
    float *_field17;
    unsigned int _field18;
    void *_field19;
};

struct Global;

struct LinkedListNode;

struct NSString {
    Class _field1;
};

struct OpaqueAudioComponentInstance;

struct OutputCoreAudio {
    void **_field1;
    struct LinkedListNode *_field2;
    struct LinkedListNode *_field3;
    void *_field4;
    unsigned int _field5;
    struct SystemI *_field6;
    struct Global *_field7;
    void *_field8;
    void *_field9;
    _Bool _field10;
    struct ChannelPool *_field11;
    _Bool _field12;
    _Bool _field13;
    struct SystemI *_field14;
    int _field15;
    struct ChannelGroupI *_field16;
    int _field17;
    _Bool _field18;
    int _field19;
    int _field20;
    struct FMOD_OS_CRITICALSECTION *_field21;
    struct FMOD_RECORDING_INFO _field22;
    struct FMOD_RECORDING_INFO *_field23;
    struct FMOD_OUTPUT_DESCRIPTION_EX _field24;
    unsigned int _field25;
    unsigned int _field26;
    unsigned int _field27;
    unsigned int _field28;
    unsigned int _field29;
    struct OpaqueAudioComponentInstance *_field30;
    _Bool _field31;
    struct Thread _field32;
    char *_field33;
    unsigned int _field34;
    unsigned int _field35;
    unsigned int _field36;
    unsigned int _field37;
    unsigned int _field38;
    _Bool _field39;
    struct OpaqueAudioComponentInstance *_field40;
    char *_field41;
    char *_field42;
    struct AudioBufferList _field43;
    int _field44;
    int _field45;
    int _field46;
    unsigned int _field47;
    _Bool _field48;
};

struct SoundI;

struct SystemI;

struct Thread {
    void **_field1;
    _Bool _field2;
    char _field3[256];
    void *_field4;
    _Bool _field5;
    void *_field6;
    void *_field7;
    struct FMOD_OS_SEMAPHORE *_field8;
    struct FMOD_OS_SEMAPHORE *_field9;
    void *_field10;
    int _field11;
};

struct _NSRange {
    unsigned int _field1;
    unsigned int _field2;
};

struct _NSZone;

struct __CFArray;

struct __CFData;

struct __CFDictionary;

