/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@class NSArray, NSString, UIImageView;

@interface CLMView : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
    NSArray *titleArr;
    NSArray *valueArr;
    NSArray *colorArr;
    NSString *title;
    UIImageView *bg;
    struct CGSize bgSize;
    struct CGSize smallSize;
    struct CGPoint center;
    float radius;
    int fontSize;
    int fontSizeMiddle;
    int fontSizeBig;
    _Bool isGray;
    _Bool isDrawContent;
    int offsetY;
}

- (void)setIsDrawContent:(_Bool)fp8;
- (_Bool)isDrawContent;
- (void)setIsGray:(_Bool)fp8;
- (_Bool)isGray;
- (void)setSmallSize:(struct CGSize)fp8;
- (struct CGSize)smallSize;
- (void)setRadius:(float)fp8;
- (float)radius;
- (void)setCenter:(struct CGPoint)fp8;
- (struct CGPoint)center;
- (void)setBg:(id)fp8;
- (id)bg;
- (void)setColorArr:(id)fp8;
- (id)colorArr;
- (void)setValueArr:(id)fp8;
- (id)valueArr;
- (void)setTitleArr:(id)fp8;
- (id)titleArr;
- (void)setTitle:(id)fp8;
- (id)title;
- (id).cxx_construct;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

