/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@class NSMutableDictionary, NSString;

@interface GameCenterManager : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
    NSMutableDictionary *earnedAchievementCache;
    NSMutableDictionary *achievementDescArray;
    id <GameCenterManagerDelegate><NSObject> delegate;
    int loginCancelCount;
    _Bool isfirstLogin;
    _Bool isAchievementInited;
    NSString *curPlayerID;
}

+ (_Bool)isGameCenterAvailable;
+ (id)sharedManager;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setAchievementDescArray:(id)fp8;
- (id)achievementDescArray;
- (void)setEarnedAchievementCache:(id)fp8;
- (id)earnedAchievementCache;
- (void)initAchievementByDownloading:(id)fp8 descriptions:(id)fp12 error:(id)fp16;
- (void)loadAchievements;
- (void)retrieveScoresForCategoryForUpload:(id)fp8 ForTimeScope:(int)fp12 ForStart:(int)fp16 ForNum:(int)fp20;
- (void)retrieveScoreByPlayerID:(id)fp8 ForCategory:(id)fp12;
- (void)retrieveScoresForCategory:(id)fp8 ForTimeScope:(int)fp12 ForStart:(int)fp16 ForNum:(int)fp20;
- (void)loadPlayerData:(id)fp8 category:(id)fp12;
- (void)retrieveFriends:(id)fp8;
- (void)mapPlayerIDtoPlayer:(id)fp8;
- (void)resetAchievements;
- (void)submitAchievement:(id)fp8 percentComplete:(double)fp12;
- (void)retrieveAllAchievementsForInit;
- (void)retrieveAllAchievements;
- (void)reportScore:(long long)fp8 forCategory:(id)fp16;
- (void)reloadHighScoresForCategory:(id)fp8;
- (void)authenticationChanged;
- (id)getLocalPlayerID;
- (id)getLocalPlayerAlias;
- (void)registerForAuthenticationNotification;
- (void)authenticateLocalUser;
- (_Bool)isLocalUserAuthenticated;
- (void)callDelegateOnMainThread:(SEL)fp8 withArg:(id)fp12 withArg2:(id)fp16 error:(id)fp20;
- (void)callDelegateOnMainThread:(SEL)fp8 withArg:(id)fp12 error:(id)fp16;
- (void)callDelegate:(SEL)fp8 withArg:(id)fp12 withArg2:(id)fp16 error:(id)fp20;
- (void)callDelegate:(SEL)fp8 withArg:(id)fp12 error:(id)fp16;
- (void)dealloc;
- (id)init;
- (void)getNSErrorDetailInfo:(id)fp8;
- (void)showNSErrorDetailInfo:(id)fp8;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)showAlertToEnableGC;
- (void)showAlertWithTitle:(id)fp8 message:(id)fp12;

@end

