/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

#import "GKAchievementHandlerDelegate-Protocol.h"

@class NSMutableArray, UIImage, UIView;

@interface GKAchievementHandler : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/ <GKAchievementHandlerDelegate>
{
    UIView *_topView;
    NSMutableArray *_queue;
    UIImage *_image;
    UIImage *_imageNoraml;
    struct CGRect kGKAchievementFrameStart;
    struct CGRect kGKAchievementFrameEnd;
}

+ (id)defaultHandler;
- (void)setImageNoraml:(id)fp8;
- (id)imageNoraml;
- (void)setImage:(id)fp8;
- (id)image;
- (id).cxx_construct;
- (void)didHideAchievementNotification:(id)fp8;
- (void)notifyAchievementTitle:(id)fp8 andMessage:(id)fp12;
- (void)notifyAchievement:(id)fp8;
- (void)dealloc;
- (id)init;
- (void)displayNotification:(id)fp8;

@end

