/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@class NSDate, NSURL;

@interface ICloudManager : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
    NSURL *icloudURL;
    id _query;
    int _index;
    _Bool isNeedRead[2];
    struct {
        id query;
        NSDate *icloudDate;
        NSURL *url;
    } icloudFileArray[2];
    Class icloudClass;
    _Bool isIcloudEnable;
    int totalDownloading;
    int curDownloading;
    _Bool isUpdatingCanceled;
    int dialogUpdateCnt;
    _Bool isForcedDialogShow;
    _Bool inited;
}

+ (id)sharedManager;
- (void)setIcloudURL:(id)fp8;
- (id)icloudURL;
- (id).cxx_construct;
- (_Bool)IsICloudEnable;
- (void)DisableICloud;
- (void)EnableICloud;
- (void)dealConflict:(id)fp8;
- (_Bool)IsICloudDownloading;
- (void)updateDownloading:(id)fp8;
- (BOOL)downloadFileIfNotAvailable:(id)fp8 iCloudDate:(id)fp12 flag:(BOOL)fp16;
- (void)queryDidFinishGathering:(id)fp8;
- (void)startDownloadQuery:(id)fp8;
- (void)saveUploadTimeLocal:(id)fp8;
- (void)updateUploading:(id)fp8;
- (void)queryDidFinishGatheringUpload:(id)fp8;
- (void)startUploadQuery:(id)fp8;
- (void)uploadICloud;
- (void)upLoadSaveToICloud:(id)fp8;
- (void)removeICloudFile:(id)fp8;
- (_Bool)isICloudAvailable;
- (void)dealloc;
- (id)init;

@end

