/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

#import "ADBannerViewDelegate-Protocol.h"
#import "AVAudioPlayerDelegate-Protocol.h"
#import "CLLocationManagerDelegate-Protocol.h"
#import "TSAlertViewDelegate-Protocol.h"
#import "UIAccelerometerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class ADBannerView, AVAudioPlayer, AdXTracking, ArtBookView, EAGLView, GCController, IPhoneViewController, MPMoviePlayerController, NSMutableArray, NSString, NSTimer, NSURL, TSAlertView, UIAlertView, UIButton, UIImageView, UILabel, UIProgressView, UITextField, UITextView, UIView, UIWindow;

@interface IPhoneAppDelegate : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/ <UIApplicationDelegate, CLLocationManagerDelegate, UIGestureRecognizerDelegate, TSAlertViewDelegate, UITextFieldDelegate, UITextViewDelegate, UIAccelerometerDelegate, AVAudioPlayerDelegate, UIAlertViewDelegate, ADBannerViewDelegate>
{
    float GlobalViewScale;
    BOOL bCanAutoRotate;
    float FadeAlpha;
    double LastFadeTime;
    UIProgressView *progressView_;
    MPMoviePlayerController *player;
    UIButton *buttons[17];
    GCController *myController;
    UILabel *scoreLabel;
    BOOL bControllerPausePressed;
    BOOL bShowMainMenu;
    BOOL bEnableContinue;
    BOOL bShowDifficultMenu;
    BOOL bShowCreditsMenu;
    BOOL bShowLegalMenu;
    int selectedButton;
    NSTimer *imageTimer;
    UIImageView *imageView;
    UIImageView *movieBackgroundImageView;
    AdXTracking *tracker;
    ArtBookView *artBookImageView;
    BOOL bMainGLViewReadyToInitialize;
    BOOL bMainGLViewInitialized;
    BOOL bUsingBackgroundMusic;
    float OSVersion;
    NSString *NextSongToPlay;
    IPhoneViewController *Controller;
    EAGLView *GLView;
    EAGLView *SecondaryGLView;
    UIWindow *Window;
    UIWindow *SecondaryWindow;
    AVAudioPlayer *MusicPlayer;
    NSTimer *FadeTimer;
    NSTimer *UE3InitCheckTimer;
    int AlertResponse;
    UIView *RootView;
    ADBannerView *BannerView;
    NSURL *iTunesURL;
    UIAlertView *UserInputAlert;
    UITextField *UserInputField;
    NSString *UserInputExec;
    NSString *UserInputCancel;
    int UserInputCharacterLimit;
    UITextView *UserInputView;
    UIView *UserView;
    UIAlertView *ConsoleAlert;
    UITextField *ConsoleTextField;
    NSMutableArray *ConsoleHistoryValues;
    int ConsoleHistoryValuesIndex;
    TSAlertView *ConsoleAlertIos7;
    TSAlertView *ConsoleAlertIos7Progress;
}

+ (id)GetDelegate;
- (void)setConsoleAlertIos7Progress:(id)fp8;
- (id)ConsoleAlertIos7Progress;
- (void)setConsoleAlertIos7:(id)fp8;
- (id)ConsoleAlertIos7;
- (void)setConsoleHistoryValuesIndex:(int)fp8;
- (int)ConsoleHistoryValuesIndex;
- (void)setConsoleHistoryValues:(id)fp8;
- (id)ConsoleHistoryValues;
- (void)setConsoleTextField:(id)fp8;
- (id)ConsoleTextField;
- (void)setConsoleAlert:(id)fp8;
- (id)ConsoleAlert;
- (void)setBControllerPausePressed:(BOOL)fp8;
- (BOOL)bControllerPausePressed;
- (void)setMyController:(id)fp8;
- (id)myController;
- (void)setMovieBackgroundImageView:(id)fp8;
- (id)movieBackgroundImageView;
- (void)setUserView:(id)fp8;
- (id)UserView;
- (void)setUserInputView:(id)fp8;
- (id)UserInputView;
- (void)setUserInputCharacterLimit:(int)fp8;
- (int)UserInputCharacterLimit;
- (void)setUserInputCancel:(id)fp8;
- (id)UserInputCancel;
- (void)setUserInputExec:(id)fp8;
- (id)UserInputExec;
- (void)setUserInputField:(id)fp8;
- (id)UserInputField;
- (void)setUserInputAlert:(id)fp8;
- (id)UserInputAlert;
- (void)setITunesURL:(id)fp8;
- (id)iTunesURL;
- (void)setBUsingBackgroundMusic:(BOOL)fp8;
- (BOOL)bUsingBackgroundMusic;
- (void)setBannerView:(id)fp8;
- (id)BannerView;
- (void)setRootView:(id)fp8;
- (id)RootView;
- (void)setAlertResponse:(int)fp8;
- (int)AlertResponse;
- (void)setUE3InitCheckTimer:(id)fp8;
- (id)UE3InitCheckTimer;
- (void)setFadeTimer:(id)fp8;
- (id)FadeTimer;
- (void)setMusicPlayer:(id)fp8;
- (id)MusicPlayer;
- (void)setSecondaryWindow:(id)fp8;
- (id)SecondaryWindow;
- (void)setWindow:(id)fp8;
- (id)Window;
- (void)setSecondaryGLView:(id)fp8;
- (id)SecondaryGLView;
- (void)setBMainGLViewInitialized:(BOOL)fp8;
- (BOOL)bMainGLViewInitialized;
- (void)setBMainGLViewReadyToInitialize:(BOOL)fp8;
- (BOOL)bMainGLViewReadyToInitialize;
- (void)setGLView:(id)fp8;
- (id)GLView;
- (void)setController:(id)fp8;
- (id)Controller;
- (void)setNextSongToPlay:(id)fp8;
- (id)NextSongToPlay;
- (float)OSVersion;
- (void)setBCanAutoRotate:(BOOL)fp8;
- (BOOL)bCanAutoRotate;
- (void)setGlobalViewScale:(float)fp8;
- (float)GlobalViewScale;
- (void)setTracker:(id)fp8;
- (id)tracker;
- (void)setImageView:(id)fp8;
- (id)imageView;
- (void)playEndingMovieSubtitle:(id)fp8;
- (void)playNextEndingMovieSubtitle;
- (_Bool)processJoyStickInput:(int)fp8 withAction:(int)fp12;
- (void)updateUISubView:(id)fp8;
- (void)unhideLabel:(id)fp8;
- (void)hideLabel:(id)fp8;
- (void)addRefCount:(id)fp8;
- (void)reduceRefCount:(id)fp8;
- (void)removeUISubView:(id)fp8;
- (void)addUISubView:(id)fp8;
- (void)createUILabels:(id)fp8;
- (void)setController;
- (void)addGCControllerNotification;
- (void)controllerDisconnected:(id)fp8;
- (void)controllerConnected:(id)fp8;
- (BOOL)isGCControllerAvailable;
- (void)setControllerText:(id)fp8;
- (void)searchController;
- (void)showMainMenu:(id)fp8;
- (unsigned long)initEffectSound:(id)fp8;
- (void)showArtBook;
- (_Bool)isPlayerNil;
- (void)IOSplayPlasmidMovie:(id)fp8:(void *)fp12;
- (void)IOSplayMovie:(id)fp8:(void *)fp12;
- (void)onButtonPress:(id)fp8;
- (void)showLegalMenu;
- (void)showCreditsMenu;
- (void)showDifficultyMenu;
- (void)onButtonTouchDown:(id)fp8;
- (void)didFinishPlaying:(id)fp8;
- (void)playVideoWithURL:(id)fp8 showControls:(BOOL)fp12;
- (void)ShowMailController:(id)fp8;
- (void)ShowMessageController:(id)fp8;
- (void)connectionDidFinishLoading:(id)fp8;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (void)openReferralURL:(id)fp8;
- (void)audioSessionDidChangeInterruptionType:(id)fp8;
- (void)dealloc;
- (void)CloseAd;
- (void)HideAdBanner;
- (void)bannerViewActionDidFinish:(id)fp8;
- (BOOL)bannerViewActionShouldBegin:(id)fp8 willLeaveApplication:(BOOL)fp12;
- (void)bannerView:(id)fp8 didFailToReceiveAdWithError:(id)fp12;
- (void)bannerViewDidLoadAd:(id)fp8;
- (void)ShowAdBanner:(id)fp8;
- (void)taAlertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)SwipeRightAction:(id)fp8;
- (void)SwipeLeftAction:(id)fp8;
- (void)SwipeDownAction:(id)fp8;
- (void)SwipeUpAction:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (BOOL)textFieldShouldClear:(id)fp8;
- (void)ShowAuthenticateConsole;
- (void)ShowConsole;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)DealInputCommand:(int)fp8;
- (void)executedInGameThread;
- (void)dismissProgressAlert;
- (void)updateMessage:(id)fp8;
- (void)updateProgress:(id)fp8;
- (void)showProgressAlert:(id)fp8;
- (void)GetUserInputMulti:(id)fp8;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (void)GetUserInput:(id)fp8;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)ShowAlert:(id)fp8;
- (void)application:(id)fp8 didReceiveLocalNotification:(id)fp12;
- (void)application:(id)fp8 didReceiveRemoteNotification:(id)fp12;
- (void)application:(id)fp8 didFailToRegisterForRemoteNotificationsWithError:(id)fp12;
- (void)application:(id)fp8 didRegisterForRemoteNotificationsWithDeviceToken:(id)fp12;
- (void)applicationDidReceiveMemoryWarning:(id)fp8;
- (void)releaseMemory;
- (void)applicationWillTerminate:(id)fp8;
- (void)applicationWillEnterForeground:(id)fp8;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)applicationDidBecomeActive:(id)fp8;
- (void)applicationWillResignActive:(id)fp8;
- (void)UE3InitializationComplete;
- (void)ScreenDetached:(id)fp8;
- (void)ScreenAttached:(id)fp8;
- (unsigned int)application:(id)fp8 supportedInterfaceOrientationsForWindow:(id)fp12;
- (void)crossfade;
- (BOOL)application:(id)fp8 didFinishLaunchingWithOptions:(id)fp12;
- (void)ProcessScreenDetached:(id)fp8;
- (void)ProcessScreenAttached:(id)fp8;
- (void)endInterruption;
- (void)beginInterruption;
- (void)didRotate:(id)fp8;
- (void)DisableSongLooping;
- (void)ResumeSong;
- (void)PauseSong;
- (void)StopSong;
- (void)PlaySong:(id)fp8;
- (void)audioPlayerEndInterruption:(id)fp8;
- (void)audioPlayerBeginInterruption:(id)fp8;
- (void)UpdatePlayerVolume;
- (void)SetRotationEnabled:(BOOL)fp8;
- (void)MainUE3GameThread:(id)fp8;
- (void)ParseCommandLineOverrides;
- (void)request:(id)fp8 contentDidDismissWithType:(struct NSString *)fp12;
- (BOOL)application:(id)fp8 openURL:(id)fp12 sourceApplication:(id)fp16 annotation:(id)fp20;
- (BOOL)application:(id)fp8 handleOpenURL:(id)fp12;
- (id)parseQueryString:(id)fp8;
- (void)reportAppOpen;

@end

