/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

#import "PHConnectionManagerDelegate-Protocol.h"

@class NSDictionary, NSString, NSURL;

@interface PHAPIRequest : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/ <PHConnectionManagerDelegate>
{
    NSURL *_URL;
    NSString *_token;
    NSString *_secret;
    NSDictionary *_signedParameters;
    NSDictionary *_additionalParameters;
    NSString *_urlPath;
    int _hashCode;
    id <PHAPIRequestDelegate> _delegate;
    unsigned int _requestStatus;
}

+ (id)v4SignatureWithMessage:(id)fp8 signatureKey:(id)fp12;
+ (id)v4SignatureWithIdentifiers:(id)fp8 token:(id)fp12 nonce:(id)fp16 signatureKey:(id)fp20;
+ (id)identifiers;
+ (id)URLByStrippingQuery:(id)fp8;
+ (id)requestWithHashCode:(int)fp8;
+ (id)requestForApp:(id)fp8 secret:(id)fp12;
+ (void)setCustomUDID:(id)fp8;
+ (id)customUDID;
+ (void)setPluginIdentifier:(id)fp8;
+ (id)pluginIdentifier;
+ (void)setOptOutStatus:(BOOL)fp8;
+ (BOOL)optOutStatus;
+ (void)setSession:(id)fp8;
+ (id)session;
+ (id)expectedSignatureValueForResponse:(id)fp8 nonce:(id)fp12 secret:(id)fp16;
+ (id)base64SignatureWithString:(id)fp8;
+ (int)cancelRequestWithHashCode:(int)fp8;
+ (void)cancelAllRequestsWithDelegate:(id)fp8;
+ (id)allRequests;
+ (void)initialize;
- (void)setRequestStatus:(unsigned int)fp8;
- (unsigned int)requestStatus;
- (void)setSignedParameters:(id)fp8;
- (id)signedParameters;
- (void)setURL:(id)fp8;
- (id)URL;
- (void)setAdditionalParameters:(id)fp8;
- (id)additionalParameters;
- (void)setHashCode:(int)fp8;
- (int)hashCode;
- (void)setUrlPath:(id)fp8;
- (id)urlPath;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)secret;
- (id)token;
- (void)constructRequestURLWithCompletionHandler:(id)fp(null);
- (void)obtainNetworkStatusWithCompletionHandler:(id)fp(null);
- (void)obtainRequestParametersWithCompletionHandler:(id)fp(null);
- (id)requestSignatureFromHttpHeaderFields:(id)fp8;
- (unsigned int)HTTPMethod;
- (void)didFailWithError:(id)fp8;
- (void)didSucceedWithResponse:(id)fp8;
- (void)processRequestResponse:(id)fp8;
- (void)connectionDidFailWithError:(id)fp8 request:(id)fp12 context:(id)fp16;
- (void)afterConnectionDidFinishLoading;
- (void)connectionDidFinishLoadingWithRequest:(id)fp8 response:(id)fp12 data:(id)fp16 context:(id)fp20;
- (void)finish;
- (void)cancel;
- (void)send;
- (void)dealloc;
- (id)signedParameterString;
- (id)basicParameters;
- (id)init;
- (id)initWithApp:(id)fp8 secret:(id)fp12;
- (id)customUDID;
- (void)setCustomUDID:(id)fp8;

@end

