/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

#import "PHURLLoaderDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class NSMutableDictionary, PHContent, UIActivityIndicatorView, UIView, UIWebView;

@interface PHContentView : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/ <UIWebViewDelegate, PHURLLoaderDelegate>
{
    PHContent *_content;
    int _orientation;
    id <PHContentViewDelegate> _delegate;
    UIWebView *_webView;
    BOOL _willAnimate;
    NSMutableDictionary *_redirects;
    UIActivityIndicatorView *_activityView;
    UIView *_targetView;
}

+ (void)enqueueContentViewInstance:(id)fp8;
+ (id)dequeueContentViewInstance;
+ (void)clearContentViews;
+ (id)allContentViews;
+ (void)initialize;
- (void)setTargetView:(id)fp8;
- (id)targetView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setContent:(id)fp8;
- (id)content;
- (void)finishBounceOut;
- (void)continueBounceOut;
- (void)bounceOut;
- (void)finishBounceIn;
- (void)continueBounceIn;
- (void)bounceIn;
- (void)loaderFailed:(id)fp8;
- (void)loaderFinished:(id)fp8;
- (BOOL)sendCallback:(id)fp8 withResponse:(id)fp12 error:(id)fp16;
- (void)handleLoadContext:(id)fp8 callback:(id)fp12;
- (void)handleDismiss:(id)fp8;
- (void)handleLaunch:(id)fp8 callback:(id)fp12;
- (void)redirectRequest:(id)fp8 toTarget:(id)fp12 action:(SEL)fp16;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)viewDidDismiss;
- (void)viewDidShow;
- (void)loadTemplate;
- (void)templateLoaded:(id)fp8;
- (void)closeView:(BOOL)fp8;
- (void)dismissWithError:(id)fp8;
- (void)dismissFromButton;
- (void)dismiss:(BOOL)fp8;
- (void)show:(BOOL)fp8;
- (struct CGAffineTransform)transformForOrientation:(int)fp8;
- (void)sizeToFitOrientation:(BOOL)fp8;
- (void)orientationDidChange;
- (void)dealloc;
- (id)activityView;
- (void)prepareForReuse;
- (void)resetRedirects;
- (id)initWithContent:(id)fp8;
- (void)contentViewsCallback:(id)fp8;

@end

