/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@class NSDictionary;

@interface PHEvent : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
    NSDictionary *_eventDictionary;
    double _timestamp;
}

+ (id)JSONStringFromDictionary:(id)fp8 error:(id *)fp12;
+ (BOOL)isPropertiesValid:(id)fp8;
+ (id)eventWithProperties:(id)fp8;
- (double)timestamp;
- (id)eventDictionary;
- (id)JSONRepresentation;
- (id)properties;
- (void)dealloc;
- (id)initWithProperties:(id)fp8;

@end

