/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@interface PHKontagentDataAccessor : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
}

+ (id)senderIDStoreKeyWithAPIKey:(id)fp8;
+ (id)persistentValuesWithTypoFileURL;
+ (id)persistentValuesFileURL;
+ (id)sharedAccessor;
- (id)senderIDForAPIKey:(id)fp8;
- (id)persistentValues;
- (void)storePrimarySenderID:(id)fp8 forAPIKey:(id)fp12;
- (id)allAPIKeySenderIDPairs;
- (id)primarySenderID;

@end

