/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHNotificationRenderer.h"

@interface PHNotificationBadgeRenderer : PHNotificationRenderer
{
}

+ (void)initialize;
- (struct CGSize)sizeForNotification:(id)fp8;
- (void)drawNotification:(id)fp8 inRect:(struct CGRect)fp12;

@end

