/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@class NSString;

@interface PHPurchase : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
    NSString *_productIdentifier;
    NSString *_item;
    int _quantity;
    NSString *_receipt;
    NSString *_callback;
}

+ (id)stringForResolution:(int)fp8;
- (void)setCallback:(id)fp8;
- (id)callback;
- (void)setReceipt:(id)fp8;
- (id)receipt;
- (void)setQuantity:(int)fp8;
- (int)quantity;
- (void)setName:(id)fp8;
- (id)name;
- (void)setProductIdentifier:(id)fp8;
- (id)productIdentifier;
- (void)reportResolution:(int)fp8;
- (void)dealloc;

@end

