/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

#import "PHAPIRequestDelegate-Protocol.h"

@class NSData, NSString;

@interface PHPushProvider : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/ <PHAPIRequestDelegate>
{
    NSString *_applicationToken;
    NSString *_applicationSecret;
    id <PHPushProviderDelegate> _delegate;
    NSData *_APNSDeviceToken;
    struct __CFArray *_registrationObservers;
}

+ (id)sharedInstance;
- (struct __CFArray *)registrationObservers;
- (void)setAPNSDeviceToken:(id)fp8;
- (id)APNSDeviceToken;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setApplicationSecret:(id)fp8;
- (id)applicationSecret;
- (void)setApplicationToken:(id)fp8;
- (id)applicationToken;
- (void)handleRemoteNotificationURL:(id)fp8;
- (void)didFailToRegisterAPNSDeviceTokenWithError:(id)fp8;
- (void)request:(id)fp8 didFailWithError:(id)fp12;
- (void)request:(id)fp8 didSucceedWithResponse:(id)fp12;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (void)registerAPNSDeviceToken:(id)fp8;
- (void)handleRemoteNotificationWithUserInfo:(id)fp8;
- (void)unregisterForPushNotifications;
- (void)registerForPushNotifications;
- (void)dealloc;
- (id)init;

@end

