/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHAdRequest.h"

@class NSString, PHContentView;

@interface PHPublisherSubContentRequest : PHAdRequest
{
    PHContentView *_source;
    NSString *_callback;
}

- (void)setCallback:(id)fp8;
- (id)callback;
- (void)setSource:(id)fp8;
- (id)source;
- (void)dealloc;
- (id)urlPath;

@end

