/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHAdRequest.h"

@class NSString;

@interface PHPublisherMetadataRequest : PHAdRequest
{
    NSString *_placement;
}

+ (id)requestForApp:(id)fp8 secret:(id)fp12 placement:(id)fp16 delegate:(id)fp20;
- (void)setPlacement:(id)fp8;
- (id)placement;
- (id)additionalParameters;
- (id)urlPath;
- (void)dealloc;
- (id)initWithApp:(id)fp8 secret:(id)fp12 placement:(id)fp16 delegate:(id)fp20;

@end

