/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHPushRequest.h"

@class NSString;

@interface PHPushDeliveryRequest : PHPushRequest
{
    NSString *_messageID;
    NSString *_contentID;
}

+ (id)requestForApp:(id)fp8 secret:(id)fp12 pushNotificationDeviceToken:(id)fp16 messageID:(id)fp20 contentUnitID:(id)fp24;
- (void)setContentID:(id)fp8;
- (id)contentID;
- (void)setMessageID:(id)fp8;
- (id)messageID;
- (id)additionalParameters;
- (void)dealloc;
- (id)initWithApp:(id)fp8 secret:(id)fp12 pushNotificationDeviceToken:(id)fp16 messageID:(id)fp20 contentUnitID:(id)fp24;

@end

