/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHAdRequest.h"

#import "PHAPIRequestDelegate-Protocol.h"
#import "PHContentViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, PHContent, UIButton, UIView;

@interface PHPublisherContentRequest : PHAdRequest <PHContentViewDelegate, PHAPIRequestDelegate>
{
    NSString *_placement;
    BOOL _animated;
    NSMutableArray *_contentViews;
    BOOL _showsOverlayImmediately;
    UIButton *_closeButton;
    UIView *_overlayWindow;
    PHContent *_content;
    int _state;
    int _targetState;
    NSString *_contentUnitID;
    NSString *_messageID;
    NSMutableDictionary *_customDimensions;
}

+ (id)requestForApp:(id)fp8 secret:(id)fp12 contentUnitID:(id)fp16 messageID:(id)fp20;
+ (id)requestForApp:(id)fp8 secret:(id)fp12 placement:(id)fp16 delegate:(id)fp20;
+ (id)existingRequestForApp:(id)fp8 secret:(id)fp12 placement:(id)fp16;
- (void)setCustomDimensions:(id)fp8;
- (id)customDimensions;
- (id)messageID;
- (void)setShowsOverlayImmediately:(BOOL)fp8;
- (BOOL)showsOverlayImmediately;
- (void)setAnimated:(BOOL)fp8;
- (BOOL)animated;
- (void)setPlacement:(id)fp8;
- (id)placement;
- (id)contentUnitID;
- (id)serializedCustomDimensions;
- (void)addDimensionsFromDictionary:(id)fp8;
- (void)setDimension:(id)fp8 forKey:(id)fp12;
- (void)requestCloseButton:(id)fp8 callback:(id)fp12 source:(id)fp16;
- (void)requestPurchases:(id)fp8 callback:(id)fp12 source:(id)fp16;
- (BOOL)isValidPurchase:(id)fp8;
- (void)requestRewards:(id)fp8 callback:(id)fp12 source:(id)fp16;
- (BOOL)isValidReward:(id)fp8;
- (id)borderColorForContentView:(id)fp8;
- (id)contentView:(id)fp8 imageForCloseButtonState:(unsigned int)fp12;
- (void)contentView:(id)fp8 didFailWithError:(id)fp12;
- (void)contentViewDidDismiss:(id)fp8;
- (void)contentViewDidLoad:(id)fp8;
- (struct CGAffineTransform)transformForOrientation:(int)fp8;
- (void)dismissToBackground;
- (void)dismissFromButton;
- (void)removeContentView:(id)fp8;
- (void)pushContent:(id)fp8;
- (void)request:(id)fp8 didFailWithError:(id)fp12;
- (void)request:(id)fp8 didSucceedWithResponse:(id)fp12;
- (void)requestSubcontent:(id)fp8 callback:(id)fp12 source:(id)fp16;
- (void)showContentIfReady;
- (void)getContent;
- (void)continueLoadingIfNeeded;
- (void)send;
- (void)preload;
- (void)didSucceedWithResponse:(id)fp8;
- (void)afterConnectionDidFinishLoading;
- (void)finish;
- (void)cancel;
- (id)additionalParameters;
- (unsigned int)HTTPMethod;
- (id)urlPath;
- (void)hideOverlayWindow;
- (void)showOverlayWindow;
- (void)hideCloseButton;
- (void)showCloseButtonBecauseOfTimeout;
- (void)placeCloseButton;
- (void)dealloc;
- (id)closeButton;
- (id)overlayWindow;
- (id)contentViews;
- (BOOL)setPublisherContentRequestState:(int)fp8;
- (int)state;
- (id)initWithApp:(id)fp8 secret:(id)fp12;
- (id)initWithApp:(id)fp8 secret:(id)fp12 contentUnitID:(id)fp16 messageID:(id)fp20;
- (id)initWithApp:(id)fp8 secret:(id)fp12 placement:(id)fp16 delegate:(id)fp20;

@end

