/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHAPIRequest.h"

@class NSData;

@interface PHPushRequest : PHAPIRequest
{
    NSData *_pushNotificationDeviceToken;
}

+ (id)requestForApp:(id)fp8 secret:(id)fp12 pushNotificationDeviceToken:(id)fp16;
- (void)setPushNotificationDeviceToken:(id)fp8;
- (id)pushNotificationDeviceToken;
- (id)additionalParameters;
- (id)urlPath;
- (void)dealloc;
- (id)initWithApp:(id)fp8 secret:(id)fp12 pushNotificationDeviceToken:(id)fp16;

@end

