/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

#import "PHConnectionManagerDelegate-Protocol.h"
#import "PHPublisherContentRequestDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface PHResourceCacher : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/ <PHConnectionManagerDelegate, UIWebViewDelegate, PHPublisherContentRequestDelegate>
{
    NSMutableArray *_cacherQueue;
    NSString *_currentlyCachingUrl;
}

+ (void)prefetchObject:(id)fp8;
+ (void)resume;
+ (void)pause;
+ (BOOL)isRequestPending:(id)fp8;
+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)sharedInstance;
- (void)setCurrentlyCachingUrl:(id)fp8;
- (id)currentlyCachingUrl;
- (void)setCacherQueue:(id)fp8;
- (id)cacherQueue;
- (void)dealloc;
- (void)connectionWasStoppedForRequest:(id)fp8 context:(id)fp12;
- (void)connectionDidFinishLoadingWithRequest:(id)fp8 response:(id)fp12 data:(id)fp16 context:(id)fp20;
- (void)connectionDidFailWithError:(id)fp8 request:(id)fp12 context:(id)fp16;
- (void)resume;
- (void)pause;
- (void)startDownloadingObject:(id)fp8;
- (id)requestForObject:(id)fp8;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)init;

@end

