/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@interface PHStringUtil : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
}

+ (id)dictionaryWithQueryString:(id)fp8;
+ (id)b64DigestForString:(id)fp8;
+ (id)hexDigestForString:(id)fp8;
+ (id)hexEncodedStringForData:(id)fp8;
+ (id)base64EncodedStringForData:(id)fp8;
+ (id)dataDigestForString:(id)fp8;
+ (id)uuid;
+ (id)stringByUrlDecodingString:(id)fp8;
+ (id)stringByUrlEncodingString:(id)fp8;
+ (id)stringByHtmlEscapingString:(id)fp8;
+ (id)stringWithQuery:(id)fp8;
+ (id)stringWithQueryQuirky:(id)fp8;

@end

