/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@interface PHTimeInGame : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
    double sessionStartTime;
}

+ (id)getInstance;
- (void)resetCounters;
- (double)getCurrentSessionDuration;
- (void)gameSessionRestart;
- (int)getCountSessions;
- (double)getSumSessionDuration;
- (void)gameSessionStopped;
- (void)gameSessionStarted;
- (id)init;

@end

