/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@class NSURL, NSURLConnection;

@interface PHURLLoader : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
    id <PHURLLoaderDelegate> _delegate;
    NSURLConnection *_connection;
    NSURL *_targetURL;
    int _totalRedirects;
    BOOL _opensFinalURLOnDevice;
    id _context;
}

+ (void)invalidateAllLoadersWithDelegate:(id)fp8;
+ (id)allLoaders;
+ (id)openDeviceURL:(id)fp8;
- (void)setContext:(id)fp8;
- (id)context;
- (void)setOpensFinalURLOnDevice:(BOOL)fp8;
- (BOOL)opensFinalURLOnDevice;
- (void)setTargetURL:(id)fp8;
- (id)targetURL;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (void)fail;
- (void)finish;
- (void)invalidate;
- (void)open;
- (void)dealloc;
- (id)init;

@end

