/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBJsonBase.h"

@interface SBJsonParser : SBJsonBase
{
    const char *c;
}

+ (void)initialize;
- (BOOL)scanIsAtEnd;
- (BOOL)scanNumber:(id *)fp8;
- (BOOL)scanHexQuad:(unsigned short *)fp8;
- (BOOL)scanUnicodeChar:(unsigned short *)fp8;
- (BOOL)scanRestOfString:(id *)fp8;
- (BOOL)scanRestOfDictionary:(id *)fp8;
- (BOOL)scanRestOfArray:(id *)fp8;
- (BOOL)scanRestOfNull:(id *)fp8;
- (BOOL)scanRestOfFalse:(id *)fp8;
- (BOOL)scanRestOfTrue:(id *)fp8;
- (BOOL)scanValue:(id *)fp8;
- (id)objectWithString:(id)fp8 error:(id *)fp12;
- (id)objectWithString:(id)fp8;

@end

