/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/.h"

@class NSMutableArray, UIImage, UIImageView, UILabel, UITextField, UITextView, UIView;

@interface TSAlertView : /UnrealEngine3/Builds/HZUW-JIAOLIN/Projects/jiaolin_hzuw-jiaolin_862/Research/BiosockES2PC/Bioshock1_PC2iOS/Bioshock_PC_JPN/Source/Unreal/../../Source/Unreal/Core/Src/
{
    UIImage *_backgroundImage;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UITextView *_messageTextView;
    UIImageView *_messageTextViewMaskImageView;
    UITextField *_inputTextField;
    NSMutableArray *_buttons;
    BOOL usesMessageTextView;
    id <TSAlertViewDelegate> delegate;
    int cancelButtonIndex;
    int firstOtherButtonIndex;
    int buttonLayout;
    float width;
    float maxHeight;
    int style;
    UIView *_customSubview;
}

- (id)customSubview;
- (int)style;
- (void)setBackgroundImage:(id)fp8;
- (void)setUsesMessageTextView:(BOOL)fp8;
- (BOOL)usesMessageTextView;
- (void)setButtonLayout:(int)fp8;
- (int)buttonLayout;
- (int)firstOtherButtonIndex;
- (int)cancelButtonIndex;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)getButtons;
- (struct CGSize)buttonsAreaSize_Stacked;
- (struct CGSize)buttonsAreaSize_SideBySide;
- (struct CGSize)inputTextFieldSize;
- (struct CGSize)messageLabelSize;
- (struct CGSize)titleLabelSize;
- (struct CGSize)recalcSizeAndLayout:(BOOL)fp8;
- (void)onButtonPress:(id)fp8;
- (void)pulse;
- (void)show;
- (void)releaseWindow:(int)fp8;
- (void)dismissWithClickedButtonIndex:(int)fp8 animated:(BOOL)fp12;
- (id)buttonTitleAtIndex:(int)fp8;
- (int)addButtonWithTitle:(id)fp8;
- (BOOL)isVisible;
- (void)setCancelButtonIndex:(int)fp8;
- (int)numberOfButtons;
- (id)message;
- (void)setMessage:(id)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (id)backgroundImage;
- (id)inputTextField;
- (id)messageTextViewMaskView;
- (id)messageTextView;
- (id)messageLabel;
- (id)titleLabel;
- (void)setCustomSubview:(id)fp8;
- (id)buttons;
- (void)onKeyboardWillHide:(id)fp8;
- (void)onKeyboardWillShow:(id)fp8;
- (void)setStyle:(int)fp8;
- (float)maxHeight;
- (void)setMaxHeight:(float)fp8;
- (float)width;
- (void)setWidth:(float)fp8;
- (void)TSAlertView_commonInit;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (id)initWithTitle:(id)fp8 message:(id)fp12 delegate:(id)fp16 cancelButtonTitle:(id)fp20 otherButtonTitles:(id)fp24;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)init;

@end

